[project]
name = "Summer-School-Jlug-Backend"
version = "0.1.0"
description = "This is my summer School project backend for jlug"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "supabase>=2.17.0",
]
